export const station_list = {
  n211_toward: [
    'Neuperlach Süd',
    'Neubiberg, W.-Heisenberg-W.',
    'Neubiberg, Neubiberg',
    'Neubiberg, Rathaus',
    'Neubiberg, Kaiserstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Anzengruberstr.',
    'Putzbrunn, Neubiberger Straße',
    'Isarweg',
  ],
  n211_backward: [
    'Isarweg',
    'Putzbrunn, Neubiberger Straße',
    'Neubiberg, Anzengruberstr.',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Kaiserstraße',
    'Neubiberg, Neubiberg',
    'Neubiberg, W.-Heisenberg-W.',
    'Neuperlach Süd',
  ],
  n212_toward: [
    'Neuperlach Süd (S)(U), München',
    'W.-Heisenberg-W., Neubiberg',
    'Neubiberg (S), Neubiberg',
    'Rathaus, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Anzengruberstr., Neubiberg',
    'Neubiberger Straße, Putzbrunn',
    'Isarweg, Putzbrunn',
    'Ödenstockach, Ort, Oedenstockach',
    'Andr.-Wagner-Str., Solalinden',
    'Am Hochstand, Solalinden',
    'Putzbrunn, Kirchenzentrum, Putzbrunn',
    'Hohenbrunner Straße, Putzbrunn',
  ],
  n212_backward: [
    'Hohenbrunner Straße, Putzbrunn',
    'Putzbrunn, Kirchenzentrum, Putzbrunn',
    'Am Hochstand, Solalinden',
    'Andr.-Wagner-Str., Solalinden',
    'Ödenstockach, Ort, Oedenstockach',
    'Isarweg, Putzbrunn',
    'Neubiberger Straße, Putzbrunn',
    'Anzengruberstr., Neubiberg',
    'Lena-Christ-Straße, Neubiberg',
    'Wotanstraße, Neubiberg',
    'Schulzstraße, Neubiberg',
    'Barbarossastraße, Neubiberg',
    'Kaiserstraße, Neubiberg',
    'Neubiberg (S), Neubiberg',
    'W.-Heisenberg-W., Neubiberg',
    'Neuperlach Süd (S)(U), München',
  ],
  n244_toward: [
    'Sauerlach (S), Sauerlach',
    'Otterloher Straße, Sauerlach',
    'Waldsiedlung, Sauerlach',
    'Münchener Str., Lanzenhaar',
    'Otterloh, Otterloh',
    'Brunnthal, Bergstraße, Brunnthal b München',
    'Brunnthal, Ort, Brunnthal b München',
    'Höhenkirchen-S., Brunnth.Str., Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-Siegertsbrunn (S), Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Lindenstraße, Höhenkirchen-Sieg.',
    'Taufki.Str., Neukirchstockach',
    'Kirchstockach, Haidstraße, Brunnthal b München',
    'Waldstraße, Neukirchstockach',
    'Gudrunsiedlg., Abzw., Brunnthal',
    'Waldbrunn, Abzw., Brunnthal',
    'Brunnthal, E.-Sänger-Ring, Brunnthal b München',
    'Brunnthal, Zusestraße, Brunnthal b München',
    'Taufkirchen, Hugo-Junkers-Str., Taufkirchen (b Mchn)',
  ],
  n244_backward: [
    'Taufkirchen, Hugo-Junkers-Str., Taufkirchen (b Mchn)',
    'Brunnthal, Zusestraße, Brunnthal b München',
    'Brunnthal, E.-Sänger-Ring, Brunnthal b München',
    'Waldbrunn, Abzw., Brunnthal',
    'Gudrunsiedlg., Abzw., Brunnthal',
    'Waldstraße, Neukirchstockach',
    'Kirchstockach, Haidstraße, Brunnthal b München',
    'Taufki.Str., Neukirchstockach',
    'Höhenkirchen-S., Lindenstraße, Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-Siegertsbrunn (S), Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Brunnth.Str., Höhenkirchen-Sieg.',
    'Brunnthal, Ort, Brunnthal b München',
    'Brunnthal, Bergstraße, Brunnthal b München',
    'Otterloh, Otterloh',
    'Münchener Str., Lanzenhaar',
    'Waldsiedlung, Sauerlach',
    'Otterloher Straße, Sauerlach',
    'Sauerlach (S), Sauerlach',
  ],
  n232: [
    'St.Emmeram (T), München',
    'Feringastraße, Unterföhring',
    'Feringastr.Ost, Unterföhring',
    'Feringastraße., Unterföhring',
    'Siedlerstraße, Unterföhring',
    'Alte Münchner Str, Unterföhring',
    'Hofäckerallee, Unterföhring',
    'Föhringer Allee, Unterföhring',
    'Unterföhring (S), Unterföhring',
    'Tulpenstraße, Unterföhring',
    'Bergstraße, Unterföhring',
    'Ahornstraße, Unterföhring',
    'Fichtenstraße, Unterföhring',
    'Ahornstraße Ost, Unterföhring',
    'Blumenstraße, Unterföhring',
    'Nelkenstraße, Unterföhring',
    'Feldstraße, Unterföhring',
    'Bergstraße., Unterföhring',
    'Rathaus, Unterföhring',
    'Föhringer Allee., Unterföhring',
    'Unterföhring (S)., Unterföhring',
    'Föhringer Allee.., Unterföhring',
    'Hofäckerallee., Unterföhring',
    'Alte Münchner Str., Unterföhring',
    'Siedlerstraße., Unterföhring',
    'Feringastraße.., Unterföhring',
    'Feringastr.Ost., Unterföhring',
    'St.Emmeram (T)., München',
  ],
};
