export const station_list = {
  n211_toward: [
    'Neuperlach Süd',
    'Neubiberg, W.-Heisenberg-W.',
    'Neubiberg',
    'Neubiberg, Rathaus',
    'Neubiberg, Kaiserstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Anzengruberstr.',
    'Putzbrunn, Neubiberger Straße',
    'Isarweg',
  ],
  n211_backward: [
    'Isarweg',
    'Putzbrunn, Neubiberger Straße',
    'Neubiberg, Anzengruberstr.',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Kaiserstraße',
    'Neubiberg',
    'Neubiberg, W.-Heisenberg-W.',
    'Neuperlach Süd',
  ],
  n212_toward: [
    'Neuperlach Süd',
    'Neubiberg, W.-Heisenberg-W.',
    'Neubiberg',
    'Neubiberg, Rathaus',
    'Neubiberg, Kaiserstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Anzengruberstr.',
    'Putzbrunn, Neubiberger Straße',
    'Isarweg',
    'Oedenstockach, Ödenstockach',
    'Solalinden, Andr.-Wagner-Str.',
    'Solalinden, Am Hochstand',
    'Putzbrunn, Kirchenzentrum',
    'Hohenbrunner Straße',
  ],
  n212_backward: [
    'Hohenbrunner Straße',
    'Putzbrunn, Kirchenzentrum',
    'Solalinden, Am Hochstand',
    'Solalinden, Andr.-Wagner-Str.',
    'Oedenstockach, Ödenstockach',
    'Isarweg',
    'Putzbrunn, Neubiberger Straße',
    'Neubiberg, Anzengruberstr.',
    'Neubiberg, Lena-Christ-Straße',
    'Neubiberg, Wotanstraße',
    'Neubiberg, Schulzstraße',
    'Neubiberg, Barbarossastraße',
    'Neubiberg, Kaiserstraße',
    'Neubiberg',
    'Neubiberg, W.-Heisenberg-W.',
    'Neuperlach Süd',
  ],
  n244_toward: [
    'Sauerlach (S)',
    'Otterloher Straße, Sauerlach',
    'Waldsiedlung, Sauerlach',
    'Münchener Str.',
    'Otterloh',
    'Brunnthal, Bergstraße, Brunnthal b München',
    'Brunnthal Ort',
    'Höhenkirchen-S., Brunnth.Str., Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-Siegertsbrunn (S)',
    'Höhenkirchen-S. Kirche',
    'Höhenkirchen-S., Lindenstraße, Höhenkirchen-Sieg.',
    'Taufki.Str., Neukirchstockach',
    'Kirchstockach, Haidstraße, Brunnthal b München',
    'Waldstraße, Neukirchstockach',
    'Gudrunsiedlg., Abzw., Brunnthal',
    'Waldbrunn, Abzw., Brunnthal',
    'Brunnthal, E.-Sänger-Ring, Brunnthal b München',
    'Brunnthal, Zusestraße',
    'Taufkirchen, Hugo-Junkers-Str.',
  ],
  n244_backward: [
    'Taufkirchen, Hugo-Junkers-Str.',
    'Brunnthal, Zusestraße',
    'Brunnthal, E.-Sänger-Ring, Brunnthal b München',
    'Waldbrunn, Abzw., Brunnthal',
    'Gudrunsiedlg., Abzw., Brunnthal',
    'Waldstraße, Neukirchstockach',
    'Kirchstockach, Haidstraße, Brunnthal b München',
    'Taufki.Str., Neukirchstockach',
    'Höhenkirchen-S., Lindenstraße, Höhenkirchen-Sieg.',
    'Höhenkirchen-S. Kirche',
    'Höhenkirchen-Siegertsbrunn (S)',
    'Höhenkirchen-S., Kirche, Höhenkirchen-Sieg.',
    'Höhenkirchen-S., Brunnth.Str., Höhenkirchen-Sieg.',
    'Brunnthal Ort',
    'Brunnthal, Bergstraße, Brunnthal b München',
    'Otterloh',
    'Münchener Str.',
    'Waldsiedlung, Sauerlach',
    'Otterloher Straße, Sauerlach',
    'Sauerlach (S)',
  ],
  n232: [
    'St.Emmeram (T)',
    'Feringastraße',
    'Feringastr.Ost',
    'Feringastraße.',
    'Siedlerstraße',
    'Alte Münchner Str',
    'Hofäckerallee',
    'Föhringer Allee',
    'Unterföhring (S)',
    'Tulpenstraße',
    'Bergstraße',
    'Ahornstraße',
    'Fichtenstraße',
    'Ahornstraße Ost',
    'Blumenstraße',
    'Nelkenstraße',
    'Feldstraße',
    'Bergstraße.',
    'Rathaus',
    'Föhringer Allee.',
    'Unterföhring (S).',
    'Föhringer Allee..',
    'Hofäckerallee.',
    'Alte Münchner Str.',
    'Siedlerstraße.',
    'Feringastraße..',
    'Feringastr.Ost.',
    'St.Emmeram (T).',
  ],
};
